### ISSUE TITLE
julia demo: Failed to open text file

### ISSUE THREAD

**Issue by ramiromagno** [jeroenjanssens/raylibr#2]
Great package! I am really excited to see where you are going with this :)

I just tried the julia demo and the code runs, launches the window but, besides the help text, the window is blank (black). I think it's because it is failing to read the files it needs. And that is because your functions do not seem to be honoring the working directory. For example it's trying to read `demo/julia_set.fs` directly from my home directory.

**Comment by jeroenjanssens** [comment]
Thank you for your kind words and for reporting this issue, @ramiromagno.

I can confirm that this is not working. I have been testing the demos by sourcing the code in the package source directory, I didn't realize that when a package is installed, only *.R* files get copied to the */demo* directory. The solution is to move any demo resources to */inst/demo_resources* and to update the demo R files.
