### ISSUE TITLE
Include more examples?

### ISSUE THREAD

**Issue by ramiromagno** [jeroenjanssens/raylibr#6]
Hi Jeroen,

What about including more examples as demos, e.g. those shown [here](https://www.raylib.com/examples.html)?

Is that something you'd think could help? If you think so, I'm glad to try to port a few of those C examples to R using `{raylibr}`.

**Comment by jeroenjanssens** [comment]
That's a great idea, @ramiromagno. There are already a couple of examples in the *demo* directory. The more the better, so any help here is greatly appreciated!

Eventually I'd like to have these examples (and perhaps even some tutorials) available on https://jeroenjanssens.github.io/raylibr/

**Comment by jeroenjanssens** [comment]
The package now contains quite a few demo's. GIFs of these demos are included in the README.

Additional examples are always welcome, but for now I'll close this issue.
